### ISSUE TITLE
Add .gitignore file to the project

### ISSUE THREAD

**Issue by kiran-thilak** [pranshi112/FoodMenu#12]
Add a .gitignore file to remove all the Unwanted/Generated files so that the size of the project can be reduced.
Current size:
![image](https://user-images.githubusercontent.com/8852764/135720146-c58d9338-3b1b-4b4f-a7e7-49d0cf4f5927.png)
Size after adding .gitignore:
![image](https://user-images.githubusercontent.com/8852764/135720132-8eae4531-d03c-407a-82dd-eaa2a706eb72.png)

### Steps
1. Add a new ```.gitignore``` file.
2. Copy contents of [unity.gitignore](https://github.com/github/gitignore/blob/master/Unity.gitignore) from GitHub's .gitignore templates
3. Remove all the tracking using ```git rm -r --cached```
4. Add the files again ```git add .```
5. Commit the code.

**Comment by kiran-thilak** [comment]
Can I wonk on this?

**Comment by pranshi112** [comment]
Yes sure, this is a nice modification.

**Comment by kiran-thilak** [comment]
@pranshi112  could you please review the changes. Now on opening the project in unity (for First Time) we may have to choose the scene from the project window.

**Comment by keshavgbpecdelhi** [comment]
Did you deleted the cached !?
Step 3 `Remove all the tracking using git rm -r --cached`
