### ISSUE TITLE
Document about WebGL and Windows Build

### ISSUE THREAD

**Issue by pranshi112** [pranshi112/FoodMenu#18]
### Description
- Create a section, `Run the Builds` in `README.md` 
- Mention the steps for both WebGL and Windows Build separately.

**Comment by Karthick47v2** [comment]
Could you explain about what will be on Documentation for Windows Build. Because for WebGL, we can give instructions for setting up a local server to run it locally. But for Windows Build, just a click is enough, no?

**Comment by pranshi112** [comment]
@Karthick47v2 For Windows Build, it would be just folder navigation and the .exe file user needs to click.
