### ISSUE TITLE
Create Menu button

### ISSUE THREAD

**Issue by pranshi112** [pranshi112/FoodMenu#3]
### Description
Add a Menu button to toggle the remaining GameObjects on the screen on and off.
- Add a UI button. Position and scale it well.
- Navigate to the `Sprites` folder, select and use the `Menu Icon` sprite on the UI button.
- Make a new script in the `Scripts` folder and add the code for the new functionality.
- Include a screenshot of your changes in the PR description.
- Do all the work in the 16:9 aspect ratio of the game view.

**Comment by NotFarFromBlonded** [comment]
Can I work on this issue?

**Comment by pranshi112** [comment]
Yes, go ahead.

**Comment by NotFarFromBlonded** [comment]
Created a PR. Kindly check.
