### ISSUE TITLE
Inform about unavailable items

### ISSUE THREAD

**Issue by pranshi112** [pranshi112/FoodMenu#7]
### Description
- Add another option in the dropdown menu and give it a random food name (which isn't available on the menu board).
- If the user orders it, a text is displayed: _Item unavailable! Order something else._ 
- `Chef` GameObject should also be disabled at this time.

**Comment by ashwin003** [comment]
Hey!
I would like to give this a shot if it is still available.

**Comment by pranshi112** [comment]
Yes sure, read the contribution guidelines and go on.

**Comment by pranshi112** [comment]
@ashwin003 Include a screenshot of your changes in the PR description so that it is easy to refer. Also, do all your work in the 16:9 aspect ratio of the game view.
