### ISSUE TITLE
Position GameObjects

### ISSUE THREAD

**Issue by pranshi112** [pranshi112/FoodMenu#8]
### Description
- Do all the work in the **16:9** aspect ratio of the game view.
- Position the `Food Items`, `Chef`, and `Order Text` GameObjects properly according to the aspect ratio.
- Scale GameObjects if necessary.
- Include screenshots of your changes in the PR description.

**Comment by kiran-thilak** [comment]
Hi, can I work on this enhancement?

**Comment by pranshi112** [comment]
Yes, read the contribution guidelines and go ahead.

**Comment by NotFarFromBlonded** [comment]
Created a PR. Kindly Check.

**Comment by pranshi112** [comment]
@NotFarFromBlonded Please ask before working on an issue because this issue is currently assigned to @kiran-thilak. If there wouldn't be any activity from the assignee for a long period, I'll review your PR.

**Comment by kiran-thilak** [comment]
Hi @pranshi112,  could you please review the changes in [Pull Request.](https://github.com/pranshi112/FoodMenu/pull/11)
